### PR TITLE
Delete VNFD of a NSD from dashboard

### PR DESCRIPTION
**Pull request by marcellom**
Fixing https://github.com/openbaton/NFVO/issues/197
Fixed in the backend, but the dashboard still shows "undefined. Error code: 403" if for example you are trying to delete the last VNFD of the NSD (forbidden by constraint). 
This is a dashboard issue since the exception message is correctly shown in the logs. @zohaibhassan122 please have a look into that.

### CODE REVIEW

**Comment by marcellom** [comment]
Messages are now shown correctly in the dashboard. If we agree that removing a VNFD from a NSD removes also the VNFD from the NFVO catalogue, then pull request can be merged.

**Comment by gc4rella** [comment]
@marcellom what happens if the VNFD is also part of other NSDs?

**Comment by marcellom** [comment]
An exception is thrown and displayed on the dashboard.

**Comment by lorenzotomasini** [comment]
A wrong reference in the dashboard commit message closed that pr

**Comment by lorenzotomasini** [comment]
@marcellom many changes on the dashboard, are they already in the master branch of the dashbaord repo?

**Comment by marcellom** [comment]
Yes, the commit https://github.com/openbaton/dashboard/commit/0bffd4def22a8e0ce76edd3d2fd19dd48bd876fc which @zohaibhassan122 did for fixing this issue is also in master now.

**Comment by gc4rella** [comment]
this should be merged, @marcellom please double check it again.

**Comment by marcellom** [comment]
It can be merged, I tested it again. Note: removing a VNFD from a NSD works now but it removes such VNFD from the catalogue too.

**Pull request merged**
